/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoTestRouteImport } from './routes/demo/test'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableDemoRouteImport } from './routes/demo/table-demo'
import { Route as DemoSidebarDemoRouteImport } from './routes/demo/sidebar-demo'
import { Route as DemoScrollAreaDemoRouteImport } from './routes/demo/scroll-area-demo'
import { Route as DemoModalTestRouteImport } from './routes/demo/modal-test'
import { Route as DemoFormTestRouteImport } from './routes/demo/form-test'
import { Route as DemoContextMenuDemoRouteImport } from './routes/demo/context-menu-demo'
import { Route as DemoCollapsibleDemoRouteImport } from './routes/demo/collapsible-demo'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTestRoute = DemoTestRouteImport.update({
  id: '/demo/test',
  path: '/demo/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableDemoRoute = DemoTableDemoRouteImport.update({
  id: '/demo/table-demo',
  path: '/demo/table-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSidebarDemoRoute = DemoSidebarDemoRouteImport.update({
  id: '/demo/sidebar-demo',
  path: '/demo/sidebar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoScrollAreaDemoRoute = DemoScrollAreaDemoRouteImport.update({
  id: '/demo/scroll-area-demo',
  path: '/demo/scroll-area-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoModalTestRoute = DemoModalTestRouteImport.update({
  id: '/demo/modal-test',
  path: '/demo/modal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormTestRoute = DemoFormTestRouteImport.update({
  id: '/demo/form-test',
  path: '/demo/form-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoContextMenuDemoRoute = DemoContextMenuDemoRouteImport.update({
  id: '/demo/context-menu-demo',
  path: '/demo/context-menu-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCollapsibleDemoRoute = DemoCollapsibleDemoRouteImport.update({
  id: '/demo/collapsible-demo',
  path: '/demo/collapsible-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo': typeof DemoIndexRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo'
    | '/admin/assets'
  id:
    | '__root__'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  DemoCollapsibleDemoRoute: typeof DemoCollapsibleDemoRoute
  DemoContextMenuDemoRoute: typeof DemoContextMenuDemoRoute
  DemoFormTestRoute: typeof DemoFormTestRoute
  DemoModalTestRoute: typeof DemoModalTestRoute
  DemoScrollAreaDemoRoute: typeof DemoScrollAreaDemoRoute
  DemoSidebarDemoRoute: typeof DemoSidebarDemoRoute
  DemoTableDemoRoute: typeof DemoTableDemoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTestRoute: typeof DemoTestRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/test': {
      id: '/demo/test'
      path: '/demo/test'
      fullPath: '/demo/test'
      preLoaderRoute: typeof DemoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table-demo': {
      id: '/demo/table-demo'
      path: '/demo/table-demo'
      fullPath: '/demo/table-demo'
      preLoaderRoute: typeof DemoTableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sidebar-demo': {
      id: '/demo/sidebar-demo'
      path: '/demo/sidebar-demo'
      fullPath: '/demo/sidebar-demo'
      preLoaderRoute: typeof DemoSidebarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/scroll-area-demo': {
      id: '/demo/scroll-area-demo'
      path: '/demo/scroll-area-demo'
      fullPath: '/demo/scroll-area-demo'
      preLoaderRoute: typeof DemoScrollAreaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/modal-test': {
      id: '/demo/modal-test'
      path: '/demo/modal-test'
      fullPath: '/demo/modal-test'
      preLoaderRoute: typeof DemoModalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form-test': {
      id: '/demo/form-test'
      path: '/demo/form-test'
      fullPath: '/demo/form-test'
      preLoaderRoute: typeof DemoFormTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/context-menu-demo': {
      id: '/demo/context-menu-demo'
      path: '/demo/context-menu-demo'
      fullPath: '/demo/context-menu-demo'
      preLoaderRoute: typeof DemoContextMenuDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/collapsible-demo': {
      id: '/demo/collapsible-demo'
      path: '/demo/collapsible-demo'
      fullPath: '/demo/collapsible-demo'
      preLoaderRoute: typeof DemoCollapsibleDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  DemoCollapsibleDemoRoute: DemoCollapsibleDemoRoute,
  DemoContextMenuDemoRoute: DemoContextMenuDemoRoute,
  DemoFormTestRoute: DemoFormTestRoute,
  DemoModalTestRoute: DemoModalTestRoute,
  DemoScrollAreaDemoRoute: DemoScrollAreaDemoRoute,
  DemoSidebarDemoRoute: DemoSidebarDemoRoute,
  DemoTableDemoRoute: DemoTableDemoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTestRoute: DemoTestRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
