/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoTestRouteImport } from './routes/demo/test'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableDemoRouteImport } from './routes/demo/table-demo'
import { Route as DemoSidebarDemoRouteImport } from './routes/demo/sidebar-demo'
import { Route as DemoScrollAreaDemoRouteImport } from './routes/demo/scroll-area-demo'
import { Route as DemoModalTestRouteImport } from './routes/demo/modal-test'
import { Route as DemoFormTestRouteImport } from './routes/demo/form-test'
import { Route as DemoContextMenuDemoRouteImport } from './routes/demo/context-menu-demo'
import { Route as DemoCollapsibleDemoRouteImport } from './routes/demo/collapsible-demo'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'
import { Route as AdminSettingsAppShellsIndexRouteImport } from './routes/admin/settings/app-shells/index'
import { Route as AdminAssetsTrialsIndexRouteImport } from './routes/admin/assets/trials/index'
import { Route as AdminAssetsTeamMembersIndexRouteImport } from './routes/admin/assets/team-members/index'
import { Route as AdminAssetsPlacesIndexRouteImport } from './routes/admin/assets/places/index'
import { Route as AdminSettingsAppShellsNewRouteImport } from './routes/admin/settings/app-shells/new'
import { Route as AdminSettingsAppShellsAppShellIdRouteImport } from './routes/admin/settings/app-shells/$appShellId'
import { Route as AdminAssetsTrialsNewRouteImport } from './routes/admin/assets/trials/new'
import { Route as AdminAssetsTrialsTrialIdRouteImport } from './routes/admin/assets/trials/$trialId'
import { Route as AdminAssetsTeamMembersNewRouteImport } from './routes/admin/assets/team-members/new'
import { Route as AdminAssetsTeamMembersTeamIdRouteImport } from './routes/admin/assets/team-members/$teamId'
import { Route as AdminAssetsPlacesNewRouteImport } from './routes/admin/assets/places/new'
import { Route as AdminAssetsPlacesPlaceIdRouteImport } from './routes/admin/assets/places/$placeId'
import { Route as AdminSettingsAppShellsAppShellIdDuplicateRouteImport } from './routes/admin/settings/app-shells/$appShellId/duplicate'
import { Route as AdminAssetsTrialsTrialIdDuplicateRouteImport } from './routes/admin/assets/trials/$trialId/duplicate'
import { Route as AdminAssetsTeamMembersTeamIdDuplicateRouteImport } from './routes/admin/assets/team-members/$teamId/duplicate'
import { Route as AdminAssetsPlacesPlaceIdDuplicateRouteImport } from './routes/admin/assets/places/$placeId/duplicate'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTestRoute = DemoTestRouteImport.update({
  id: '/demo/test',
  path: '/demo/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableDemoRoute = DemoTableDemoRouteImport.update({
  id: '/demo/table-demo',
  path: '/demo/table-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSidebarDemoRoute = DemoSidebarDemoRouteImport.update({
  id: '/demo/sidebar-demo',
  path: '/demo/sidebar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoScrollAreaDemoRoute = DemoScrollAreaDemoRouteImport.update({
  id: '/demo/scroll-area-demo',
  path: '/demo/scroll-area-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoModalTestRoute = DemoModalTestRouteImport.update({
  id: '/demo/modal-test',
  path: '/demo/modal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormTestRoute = DemoFormTestRouteImport.update({
  id: '/demo/form-test',
  path: '/demo/form-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoContextMenuDemoRoute = DemoContextMenuDemoRouteImport.update({
  id: '/demo/context-menu-demo',
  path: '/demo/context-menu-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCollapsibleDemoRoute = DemoCollapsibleDemoRouteImport.update({
  id: '/demo/collapsible-demo',
  path: '/demo/collapsible-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsAppShellsIndexRoute =
  AdminSettingsAppShellsIndexRouteImport.update({
    id: '/settings/app-shells/',
    path: '/settings/app-shells/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTrialsIndexRoute = AdminAssetsTrialsIndexRouteImport.update({
  id: '/assets/trials/',
  path: '/assets/trials/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsTeamMembersIndexRoute =
  AdminAssetsTeamMembersIndexRouteImport.update({
    id: '/assets/team-members/',
    path: '/assets/team-members/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsPlacesIndexRoute = AdminAssetsPlacesIndexRouteImport.update({
  id: '/assets/places/',
  path: '/assets/places/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsAppShellsNewRoute =
  AdminSettingsAppShellsNewRouteImport.update({
    id: '/settings/app-shells/new',
    path: '/settings/app-shells/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsAppShellsAppShellIdRoute =
  AdminSettingsAppShellsAppShellIdRouteImport.update({
    id: '/settings/app-shells/$appShellId',
    path: '/settings/app-shells/$appShellId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTrialsNewRoute = AdminAssetsTrialsNewRouteImport.update({
  id: '/assets/trials/new',
  path: '/assets/trials/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsTrialsTrialIdRoute =
  AdminAssetsTrialsTrialIdRouteImport.update({
    id: '/assets/trials/$trialId',
    path: '/assets/trials/$trialId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTeamMembersNewRoute =
  AdminAssetsTeamMembersNewRouteImport.update({
    id: '/assets/team-members/new',
    path: '/assets/team-members/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTeamMembersTeamIdRoute =
  AdminAssetsTeamMembersTeamIdRouteImport.update({
    id: '/assets/team-members/$teamId',
    path: '/assets/team-members/$teamId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsPlacesNewRoute = AdminAssetsPlacesNewRouteImport.update({
  id: '/assets/places/new',
  path: '/assets/places/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsPlacesPlaceIdRoute =
  AdminAssetsPlacesPlaceIdRouteImport.update({
    id: '/assets/places/$placeId',
    path: '/assets/places/$placeId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsAppShellsAppShellIdDuplicateRoute =
  AdminSettingsAppShellsAppShellIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminSettingsAppShellsAppShellIdRoute,
  } as any)
const AdminAssetsTrialsTrialIdDuplicateRoute =
  AdminAssetsTrialsTrialIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsTrialsTrialIdRoute,
  } as any)
const AdminAssetsTeamMembersTeamIdDuplicateRoute =
  AdminAssetsTeamMembersTeamIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsTeamMembersTeamIdRoute,
  } as any)
const AdminAssetsPlacesPlaceIdDuplicateRoute =
  AdminAssetsPlacesPlaceIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsPlacesPlaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/assets/places/': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members/': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials/': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells/': typeof AdminSettingsAppShellsIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo': typeof DemoIndexRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/assets/places': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells': typeof AdminSettingsAppShellsIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/assets/places/': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members/': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials/': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells/': typeof AdminSettingsAppShellsIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/assets/'
    | '/admin/settings/'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/assets/places/'
    | '/admin/assets/team-members/'
    | '/admin/assets/trials/'
    | '/admin/settings/app-shells/'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo'
    | '/admin/assets'
    | '/admin/settings'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/assets/places'
    | '/admin/assets/team-members'
    | '/admin/assets/trials'
    | '/admin/settings/app-shells'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  id:
    | '__root__'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/assets/'
    | '/admin/settings/'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/assets/places/'
    | '/admin/assets/team-members/'
    | '/admin/assets/trials/'
    | '/admin/settings/app-shells/'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  DemoCollapsibleDemoRoute: typeof DemoCollapsibleDemoRoute
  DemoContextMenuDemoRoute: typeof DemoContextMenuDemoRoute
  DemoFormTestRoute: typeof DemoFormTestRoute
  DemoModalTestRoute: typeof DemoModalTestRoute
  DemoScrollAreaDemoRoute: typeof DemoScrollAreaDemoRoute
  DemoSidebarDemoRoute: typeof DemoSidebarDemoRoute
  DemoTableDemoRoute: typeof DemoTableDemoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTestRoute: typeof DemoTestRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/test': {
      id: '/demo/test'
      path: '/demo/test'
      fullPath: '/demo/test'
      preLoaderRoute: typeof DemoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table-demo': {
      id: '/demo/table-demo'
      path: '/demo/table-demo'
      fullPath: '/demo/table-demo'
      preLoaderRoute: typeof DemoTableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sidebar-demo': {
      id: '/demo/sidebar-demo'
      path: '/demo/sidebar-demo'
      fullPath: '/demo/sidebar-demo'
      preLoaderRoute: typeof DemoSidebarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/scroll-area-demo': {
      id: '/demo/scroll-area-demo'
      path: '/demo/scroll-area-demo'
      fullPath: '/demo/scroll-area-demo'
      preLoaderRoute: typeof DemoScrollAreaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/modal-test': {
      id: '/demo/modal-test'
      path: '/demo/modal-test'
      fullPath: '/demo/modal-test'
      preLoaderRoute: typeof DemoModalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form-test': {
      id: '/demo/form-test'
      path: '/demo/form-test'
      fullPath: '/demo/form-test'
      preLoaderRoute: typeof DemoFormTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/context-menu-demo': {
      id: '/demo/context-menu-demo'
      path: '/demo/context-menu-demo'
      fullPath: '/demo/context-menu-demo'
      preLoaderRoute: typeof DemoContextMenuDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/collapsible-demo': {
      id: '/demo/collapsible-demo'
      path: '/demo/collapsible-demo'
      fullPath: '/demo/collapsible-demo'
      preLoaderRoute: typeof DemoCollapsibleDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/': {
      id: '/admin/settings/app-shells/'
      path: '/settings/app-shells'
      fullPath: '/admin/settings/app-shells/'
      preLoaderRoute: typeof AdminSettingsAppShellsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/trials/': {
      id: '/admin/assets/trials/'
      path: '/assets/trials'
      fullPath: '/admin/assets/trials/'
      preLoaderRoute: typeof AdminAssetsTrialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/': {
      id: '/admin/assets/team-members/'
      path: '/assets/team-members'
      fullPath: '/admin/assets/team-members/'
      preLoaderRoute: typeof AdminAssetsTeamMembersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/': {
      id: '/admin/assets/places/'
      path: '/assets/places'
      fullPath: '/admin/assets/places/'
      preLoaderRoute: typeof AdminAssetsPlacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/new': {
      id: '/admin/settings/app-shells/new'
      path: '/settings/app-shells/new'
      fullPath: '/admin/settings/app-shells/new'
      preLoaderRoute: typeof AdminSettingsAppShellsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/$appShellId': {
      id: '/admin/settings/app-shells/$appShellId'
      path: '/settings/app-shells/$appShellId'
      fullPath: '/admin/settings/app-shells/$appShellId'
      preLoaderRoute: typeof AdminSettingsAppShellsAppShellIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/trials/new': {
      id: '/admin/assets/trials/new'
      path: '/assets/trials/new'
      fullPath: '/admin/assets/trials/new'
      preLoaderRoute: typeof AdminAssetsTrialsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/trials/$trialId': {
      id: '/admin/assets/trials/$trialId'
      path: '/assets/trials/$trialId'
      fullPath: '/admin/assets/trials/$trialId'
      preLoaderRoute: typeof AdminAssetsTrialsTrialIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/new': {
      id: '/admin/assets/team-members/new'
      path: '/assets/team-members/new'
      fullPath: '/admin/assets/team-members/new'
      preLoaderRoute: typeof AdminAssetsTeamMembersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/$teamId': {
      id: '/admin/assets/team-members/$teamId'
      path: '/assets/team-members/$teamId'
      fullPath: '/admin/assets/team-members/$teamId'
      preLoaderRoute: typeof AdminAssetsTeamMembersTeamIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/new': {
      id: '/admin/assets/places/new'
      path: '/assets/places/new'
      fullPath: '/admin/assets/places/new'
      preLoaderRoute: typeof AdminAssetsPlacesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/$placeId': {
      id: '/admin/assets/places/$placeId'
      path: '/assets/places/$placeId'
      fullPath: '/admin/assets/places/$placeId'
      preLoaderRoute: typeof AdminAssetsPlacesPlaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/$appShellId/duplicate': {
      id: '/admin/settings/app-shells/$appShellId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/settings/app-shells/$appShellId/duplicate'
      preLoaderRoute: typeof AdminSettingsAppShellsAppShellIdDuplicateRouteImport
      parentRoute: typeof AdminSettingsAppShellsAppShellIdRoute
    }
    '/admin/assets/trials/$trialId/duplicate': {
      id: '/admin/assets/trials/$trialId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/trials/$trialId/duplicate'
      preLoaderRoute: typeof AdminAssetsTrialsTrialIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsTrialsTrialIdRoute
    }
    '/admin/assets/team-members/$teamId/duplicate': {
      id: '/admin/assets/team-members/$teamId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/team-members/$teamId/duplicate'
      preLoaderRoute: typeof AdminAssetsTeamMembersTeamIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsTeamMembersTeamIdRoute
    }
    '/admin/assets/places/$placeId/duplicate': {
      id: '/admin/assets/places/$placeId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/places/$placeId/duplicate'
      preLoaderRoute: typeof AdminAssetsPlacesPlaceIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsPlacesPlaceIdRoute
    }
  }
}

interface AdminAssetsPlacesPlaceIdRouteChildren {
  AdminAssetsPlacesPlaceIdDuplicateRoute: typeof AdminAssetsPlacesPlaceIdDuplicateRoute
}

const AdminAssetsPlacesPlaceIdRouteChildren: AdminAssetsPlacesPlaceIdRouteChildren =
  {
    AdminAssetsPlacesPlaceIdDuplicateRoute:
      AdminAssetsPlacesPlaceIdDuplicateRoute,
  }

const AdminAssetsPlacesPlaceIdRouteWithChildren =
  AdminAssetsPlacesPlaceIdRoute._addFileChildren(
    AdminAssetsPlacesPlaceIdRouteChildren,
  )

interface AdminAssetsTeamMembersTeamIdRouteChildren {
  AdminAssetsTeamMembersTeamIdDuplicateRoute: typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
}

const AdminAssetsTeamMembersTeamIdRouteChildren: AdminAssetsTeamMembersTeamIdRouteChildren =
  {
    AdminAssetsTeamMembersTeamIdDuplicateRoute:
      AdminAssetsTeamMembersTeamIdDuplicateRoute,
  }

const AdminAssetsTeamMembersTeamIdRouteWithChildren =
  AdminAssetsTeamMembersTeamIdRoute._addFileChildren(
    AdminAssetsTeamMembersTeamIdRouteChildren,
  )

interface AdminAssetsTrialsTrialIdRouteChildren {
  AdminAssetsTrialsTrialIdDuplicateRoute: typeof AdminAssetsTrialsTrialIdDuplicateRoute
}

const AdminAssetsTrialsTrialIdRouteChildren: AdminAssetsTrialsTrialIdRouteChildren =
  {
    AdminAssetsTrialsTrialIdDuplicateRoute:
      AdminAssetsTrialsTrialIdDuplicateRoute,
  }

const AdminAssetsTrialsTrialIdRouteWithChildren =
  AdminAssetsTrialsTrialIdRoute._addFileChildren(
    AdminAssetsTrialsTrialIdRouteChildren,
  )

interface AdminSettingsAppShellsAppShellIdRouteChildren {
  AdminSettingsAppShellsAppShellIdDuplicateRoute: typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}

const AdminSettingsAppShellsAppShellIdRouteChildren: AdminSettingsAppShellsAppShellIdRouteChildren =
  {
    AdminSettingsAppShellsAppShellIdDuplicateRoute:
      AdminSettingsAppShellsAppShellIdDuplicateRoute,
  }

const AdminSettingsAppShellsAppShellIdRouteWithChildren =
  AdminSettingsAppShellsAppShellIdRoute._addFileChildren(
    AdminSettingsAppShellsAppShellIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminAssetsPlacesPlaceIdRoute: typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  AdminAssetsPlacesNewRoute: typeof AdminAssetsPlacesNewRoute
  AdminAssetsTeamMembersTeamIdRoute: typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  AdminAssetsTeamMembersNewRoute: typeof AdminAssetsTeamMembersNewRoute
  AdminAssetsTrialsTrialIdRoute: typeof AdminAssetsTrialsTrialIdRouteWithChildren
  AdminAssetsTrialsNewRoute: typeof AdminAssetsTrialsNewRoute
  AdminSettingsAppShellsAppShellIdRoute: typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  AdminSettingsAppShellsNewRoute: typeof AdminSettingsAppShellsNewRoute
  AdminAssetsPlacesIndexRoute: typeof AdminAssetsPlacesIndexRoute
  AdminAssetsTeamMembersIndexRoute: typeof AdminAssetsTeamMembersIndexRoute
  AdminAssetsTrialsIndexRoute: typeof AdminAssetsTrialsIndexRoute
  AdminSettingsAppShellsIndexRoute: typeof AdminSettingsAppShellsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminAssetsPlacesPlaceIdRoute: AdminAssetsPlacesPlaceIdRouteWithChildren,
  AdminAssetsPlacesNewRoute: AdminAssetsPlacesNewRoute,
  AdminAssetsTeamMembersTeamIdRoute:
    AdminAssetsTeamMembersTeamIdRouteWithChildren,
  AdminAssetsTeamMembersNewRoute: AdminAssetsTeamMembersNewRoute,
  AdminAssetsTrialsTrialIdRoute: AdminAssetsTrialsTrialIdRouteWithChildren,
  AdminAssetsTrialsNewRoute: AdminAssetsTrialsNewRoute,
  AdminSettingsAppShellsAppShellIdRoute:
    AdminSettingsAppShellsAppShellIdRouteWithChildren,
  AdminSettingsAppShellsNewRoute: AdminSettingsAppShellsNewRoute,
  AdminAssetsPlacesIndexRoute: AdminAssetsPlacesIndexRoute,
  AdminAssetsTeamMembersIndexRoute: AdminAssetsTeamMembersIndexRoute,
  AdminAssetsTrialsIndexRoute: AdminAssetsTrialsIndexRoute,
  AdminSettingsAppShellsIndexRoute: AdminSettingsAppShellsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  DemoCollapsibleDemoRoute: DemoCollapsibleDemoRoute,
  DemoContextMenuDemoRoute: DemoContextMenuDemoRoute,
  DemoFormTestRoute: DemoFormTestRoute,
  DemoModalTestRoute: DemoModalTestRoute,
  DemoScrollAreaDemoRoute: DemoScrollAreaDemoRoute,
  DemoSidebarDemoRoute: DemoSidebarDemoRoute,
  DemoTableDemoRoute: DemoTableDemoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTestRoute: DemoTestRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
