/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoTestRouteImport } from './routes/demo/test'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableDemoRouteImport } from './routes/demo/table-demo'
import { Route as DemoSidebarDemoRouteImport } from './routes/demo/sidebar-demo'
import { Route as DemoScrollAreaDemoRouteImport } from './routes/demo/scroll-area-demo'
import { Route as DemoModalTestRouteImport } from './routes/demo/modal-test'
import { Route as DemoFormTestRouteImport } from './routes/demo/form-test'
import { Route as DemoContextMenuDemoRouteImport } from './routes/demo/context-menu-demo'
import { Route as DemoCollapsibleDemoRouteImport } from './routes/demo/collapsible-demo'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups/index'
import { Route as AdminContractsIndexRouteImport } from './routes/admin/contracts/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminGroupsNewRouteImport } from './routes/admin/groups/new'
import { Route as AdminGroupsGroupIdRouteImport } from './routes/admin/groups/$groupId'
import { Route as AdminContractsNewRouteImport } from './routes/admin/contracts/new'
import { Route as AdminContractsContractIdRouteImport } from './routes/admin/contracts/$contractId'
import { Route as AdminClientsNewRouteImport } from './routes/admin/clients/new'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients/$clientId'
import { Route as AdminSettingsModulesIndexRouteImport } from './routes/admin/settings/modules/index'
import { Route as AdminSettingsFontsIndexRouteImport } from './routes/admin/settings/fonts/index'
import { Route as AdminSettingsAppShellsIndexRouteImport } from './routes/admin/settings/app-shells/index'
import { Route as AdminAssetsTrialsIndexRouteImport } from './routes/admin/assets/trials/index'
import { Route as AdminAssetsTeamMembersIndexRouteImport } from './routes/admin/assets/team-members/index'
import { Route as AdminAssetsPlacesIndexRouteImport } from './routes/admin/assets/places/index'
import { Route as AdminUsersUserIdDuplicateRouteImport } from './routes/admin/users/$userId/duplicate'
import { Route as AdminSettingsFontsNewRouteImport } from './routes/admin/settings/fonts/new'
import { Route as AdminSettingsFontsFontIdRouteImport } from './routes/admin/settings/fonts/$fontId'
import { Route as AdminSettingsAppShellsNewRouteImport } from './routes/admin/settings/app-shells/new'
import { Route as AdminSettingsAppShellsAppShellIdRouteImport } from './routes/admin/settings/app-shells/$appShellId'
import { Route as AdminGroupsGroupIdDuplicateRouteImport } from './routes/admin/groups/$groupId/duplicate'
import { Route as AdminContractsContractIdDuplicateRouteImport } from './routes/admin/contracts/$contractId/duplicate'
import { Route as AdminAssetsTrialsNewRouteImport } from './routes/admin/assets/trials/new'
import { Route as AdminAssetsTrialsTrialIdRouteImport } from './routes/admin/assets/trials/$trialId'
import { Route as AdminAssetsTeamMembersNewRouteImport } from './routes/admin/assets/team-members/new'
import { Route as AdminAssetsTeamMembersTeamIdRouteImport } from './routes/admin/assets/team-members/$teamId'
import { Route as AdminAssetsPlacesNewRouteImport } from './routes/admin/assets/places/new'
import { Route as AdminAssetsPlacesPlaceIdRouteImport } from './routes/admin/assets/places/$placeId'
import { Route as AdminSettingsAppShellsAppShellIdDuplicateRouteImport } from './routes/admin/settings/app-shells/$appShellId/duplicate'
import { Route as AdminAssetsTrialsTrialIdDuplicateRouteImport } from './routes/admin/assets/trials/$trialId/duplicate'
import { Route as AdminAssetsTeamMembersTeamIdDuplicateRouteImport } from './routes/admin/assets/team-members/$teamId/duplicate'
import { Route as AdminAssetsPlacesPlaceIdDuplicateRouteImport } from './routes/admin/assets/places/$placeId/duplicate'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTestRoute = DemoTestRouteImport.update({
  id: '/demo/test',
  path: '/demo/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableDemoRoute = DemoTableDemoRouteImport.update({
  id: '/demo/table-demo',
  path: '/demo/table-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSidebarDemoRoute = DemoSidebarDemoRouteImport.update({
  id: '/demo/sidebar-demo',
  path: '/demo/sidebar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoScrollAreaDemoRoute = DemoScrollAreaDemoRouteImport.update({
  id: '/demo/scroll-area-demo',
  path: '/demo/scroll-area-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoModalTestRoute = DemoModalTestRouteImport.update({
  id: '/demo/modal-test',
  path: '/demo/modal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormTestRoute = DemoFormTestRouteImport.update({
  id: '/demo/form-test',
  path: '/demo/form-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoContextMenuDemoRoute = DemoContextMenuDemoRouteImport.update({
  id: '/demo/context-menu-demo',
  path: '/demo/context-menu-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCollapsibleDemoRoute = DemoCollapsibleDemoRouteImport.update({
  id: '/demo/collapsible-demo',
  path: '/demo/collapsible-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsIndexRoute = AdminContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsNewRoute = AdminGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsGroupIdRoute = AdminGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsNewRoute = AdminContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsContractIdRoute =
  AdminContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsModulesIndexRoute =
  AdminSettingsModulesIndexRouteImport.update({
    id: '/settings/modules/',
    path: '/settings/modules/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsFontsIndexRoute = AdminSettingsFontsIndexRouteImport.update({
  id: '/settings/fonts/',
  path: '/settings/fonts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsAppShellsIndexRoute =
  AdminSettingsAppShellsIndexRouteImport.update({
    id: '/settings/app-shells/',
    path: '/settings/app-shells/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTrialsIndexRoute = AdminAssetsTrialsIndexRouteImport.update({
  id: '/assets/trials/',
  path: '/assets/trials/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsTeamMembersIndexRoute =
  AdminAssetsTeamMembersIndexRouteImport.update({
    id: '/assets/team-members/',
    path: '/assets/team-members/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsPlacesIndexRoute = AdminAssetsPlacesIndexRouteImport.update({
  id: '/assets/places/',
  path: '/assets/places/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdDuplicateRoute =
  AdminUsersUserIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminUsersUserIdRoute,
  } as any)
const AdminSettingsFontsNewRoute = AdminSettingsFontsNewRouteImport.update({
  id: '/settings/fonts/new',
  path: '/settings/fonts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsFontsFontIdRoute =
  AdminSettingsFontsFontIdRouteImport.update({
    id: '/settings/fonts/$fontId',
    path: '/settings/fonts/$fontId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsAppShellsNewRoute =
  AdminSettingsAppShellsNewRouteImport.update({
    id: '/settings/app-shells/new',
    path: '/settings/app-shells/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsAppShellsAppShellIdRoute =
  AdminSettingsAppShellsAppShellIdRouteImport.update({
    id: '/settings/app-shells/$appShellId',
    path: '/settings/app-shells/$appShellId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGroupsGroupIdDuplicateRoute =
  AdminGroupsGroupIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminGroupsGroupIdRoute,
  } as any)
const AdminContractsContractIdDuplicateRoute =
  AdminContractsContractIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminContractsContractIdRoute,
  } as any)
const AdminAssetsTrialsNewRoute = AdminAssetsTrialsNewRouteImport.update({
  id: '/assets/trials/new',
  path: '/assets/trials/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsTrialsTrialIdRoute =
  AdminAssetsTrialsTrialIdRouteImport.update({
    id: '/assets/trials/$trialId',
    path: '/assets/trials/$trialId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTeamMembersNewRoute =
  AdminAssetsTeamMembersNewRouteImport.update({
    id: '/assets/team-members/new',
    path: '/assets/team-members/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsTeamMembersTeamIdRoute =
  AdminAssetsTeamMembersTeamIdRouteImport.update({
    id: '/assets/team-members/$teamId',
    path: '/assets/team-members/$teamId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsPlacesNewRoute = AdminAssetsPlacesNewRouteImport.update({
  id: '/assets/places/new',
  path: '/assets/places/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsPlacesPlaceIdRoute =
  AdminAssetsPlacesPlaceIdRouteImport.update({
    id: '/assets/places/$placeId',
    path: '/assets/places/$placeId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsAppShellsAppShellIdDuplicateRoute =
  AdminSettingsAppShellsAppShellIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminSettingsAppShellsAppShellIdRoute,
  } as any)
const AdminAssetsTrialsTrialIdDuplicateRoute =
  AdminAssetsTrialsTrialIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsTrialsTrialIdRoute,
  } as any)
const AdminAssetsTeamMembersTeamIdDuplicateRoute =
  AdminAssetsTeamMembersTeamIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsTeamMembersTeamIdRoute,
  } as any)
const AdminAssetsPlacesPlaceIdDuplicateRoute =
  AdminAssetsPlacesPlaceIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => AdminAssetsPlacesPlaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$contractId': typeof AdminContractsContractIdRouteWithChildren
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRouteWithChildren
  '/admin/groups/new': typeof AdminGroupsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/contracts/$contractId/duplicate': typeof AdminContractsContractIdDuplicateRoute
  '/admin/groups/$groupId/duplicate': typeof AdminGroupsGroupIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/settings/fonts/$fontId': typeof AdminSettingsFontsFontIdRoute
  '/admin/settings/fonts/new': typeof AdminSettingsFontsNewRoute
  '/admin/users/$userId/duplicate': typeof AdminUsersUserIdDuplicateRoute
  '/admin/assets/places/': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members/': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials/': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells/': typeof AdminSettingsAppShellsIndexRoute
  '/admin/settings/fonts/': typeof AdminSettingsFontsIndexRoute
  '/admin/settings/modules/': typeof AdminSettingsModulesIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo': typeof DemoIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$contractId': typeof AdminContractsContractIdRouteWithChildren
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRouteWithChildren
  '/admin/groups/new': typeof AdminGroupsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/contracts': typeof AdminContractsIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/contracts/$contractId/duplicate': typeof AdminContractsContractIdDuplicateRoute
  '/admin/groups/$groupId/duplicate': typeof AdminGroupsGroupIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/settings/fonts/$fontId': typeof AdminSettingsFontsFontIdRoute
  '/admin/settings/fonts/new': typeof AdminSettingsFontsNewRoute
  '/admin/users/$userId/duplicate': typeof AdminUsersUserIdDuplicateRoute
  '/admin/assets/places': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells': typeof AdminSettingsAppShellsIndexRoute
  '/admin/settings/fonts': typeof AdminSettingsFontsIndexRoute
  '/admin/settings/modules': typeof AdminSettingsModulesIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/demo/collapsible-demo': typeof DemoCollapsibleDemoRoute
  '/demo/context-menu-demo': typeof DemoContextMenuDemoRoute
  '/demo/form-test': typeof DemoFormTestRoute
  '/demo/modal-test': typeof DemoModalTestRoute
  '/demo/scroll-area-demo': typeof DemoScrollAreaDemoRoute
  '/demo/sidebar-demo': typeof DemoSidebarDemoRoute
  '/demo/table-demo': typeof DemoTableDemoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/test': typeof DemoTestRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$contractId': typeof AdminContractsContractIdRouteWithChildren
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRouteWithChildren
  '/admin/groups/new': typeof AdminGroupsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/assets/places/$placeId': typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  '/admin/assets/places/new': typeof AdminAssetsPlacesNewRoute
  '/admin/assets/team-members/$teamId': typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  '/admin/assets/team-members/new': typeof AdminAssetsTeamMembersNewRoute
  '/admin/assets/trials/$trialId': typeof AdminAssetsTrialsTrialIdRouteWithChildren
  '/admin/assets/trials/new': typeof AdminAssetsTrialsNewRoute
  '/admin/contracts/$contractId/duplicate': typeof AdminContractsContractIdDuplicateRoute
  '/admin/groups/$groupId/duplicate': typeof AdminGroupsGroupIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId': typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  '/admin/settings/app-shells/new': typeof AdminSettingsAppShellsNewRoute
  '/admin/settings/fonts/$fontId': typeof AdminSettingsFontsFontIdRoute
  '/admin/settings/fonts/new': typeof AdminSettingsFontsNewRoute
  '/admin/users/$userId/duplicate': typeof AdminUsersUserIdDuplicateRoute
  '/admin/assets/places/': typeof AdminAssetsPlacesIndexRoute
  '/admin/assets/team-members/': typeof AdminAssetsTeamMembersIndexRoute
  '/admin/assets/trials/': typeof AdminAssetsTrialsIndexRoute
  '/admin/settings/app-shells/': typeof AdminSettingsAppShellsIndexRoute
  '/admin/settings/fonts/': typeof AdminSettingsFontsIndexRoute
  '/admin/settings/modules/': typeof AdminSettingsModulesIndexRoute
  '/admin/assets/places/$placeId/duplicate': typeof AdminAssetsPlacesPlaceIdDuplicateRoute
  '/admin/assets/team-members/$teamId/duplicate': typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
  '/admin/assets/trials/$trialId/duplicate': typeof AdminAssetsTrialsTrialIdDuplicateRoute
  '/admin/settings/app-shells/$appShellId/duplicate': typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/groups/$groupId'
    | '/admin/groups/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/assets/'
    | '/admin/clients/'
    | '/admin/contracts/'
    | '/admin/groups/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/contracts/$contractId/duplicate'
    | '/admin/groups/$groupId/duplicate'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/settings/fonts/$fontId'
    | '/admin/settings/fonts/new'
    | '/admin/users/$userId/duplicate'
    | '/admin/assets/places/'
    | '/admin/assets/team-members/'
    | '/admin/assets/trials/'
    | '/admin/settings/app-shells/'
    | '/admin/settings/fonts/'
    | '/admin/settings/modules/'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/groups/$groupId'
    | '/admin/groups/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/assets'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/groups'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/contracts/$contractId/duplicate'
    | '/admin/groups/$groupId/duplicate'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/settings/fonts/$fontId'
    | '/admin/settings/fonts/new'
    | '/admin/users/$userId/duplicate'
    | '/admin/assets/places'
    | '/admin/assets/team-members'
    | '/admin/assets/trials'
    | '/admin/settings/app-shells'
    | '/admin/settings/fonts'
    | '/admin/settings/modules'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  id:
    | '__root__'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/demo/collapsible-demo'
    | '/demo/context-menu-demo'
    | '/demo/form-test'
    | '/demo/modal-test'
    | '/demo/scroll-area-demo'
    | '/demo/sidebar-demo'
    | '/demo/table-demo'
    | '/demo/tanstack-query'
    | '/demo/test'
    | '/demo/'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/groups/$groupId'
    | '/admin/groups/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/assets/'
    | '/admin/clients/'
    | '/admin/contracts/'
    | '/admin/groups/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/assets/places/$placeId'
    | '/admin/assets/places/new'
    | '/admin/assets/team-members/$teamId'
    | '/admin/assets/team-members/new'
    | '/admin/assets/trials/$trialId'
    | '/admin/assets/trials/new'
    | '/admin/contracts/$contractId/duplicate'
    | '/admin/groups/$groupId/duplicate'
    | '/admin/settings/app-shells/$appShellId'
    | '/admin/settings/app-shells/new'
    | '/admin/settings/fonts/$fontId'
    | '/admin/settings/fonts/new'
    | '/admin/users/$userId/duplicate'
    | '/admin/assets/places/'
    | '/admin/assets/team-members/'
    | '/admin/assets/trials/'
    | '/admin/settings/app-shells/'
    | '/admin/settings/fonts/'
    | '/admin/settings/modules/'
    | '/admin/assets/places/$placeId/duplicate'
    | '/admin/assets/team-members/$teamId/duplicate'
    | '/admin/assets/trials/$trialId/duplicate'
    | '/admin/settings/app-shells/$appShellId/duplicate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  DemoCollapsibleDemoRoute: typeof DemoCollapsibleDemoRoute
  DemoContextMenuDemoRoute: typeof DemoContextMenuDemoRoute
  DemoFormTestRoute: typeof DemoFormTestRoute
  DemoModalTestRoute: typeof DemoModalTestRoute
  DemoScrollAreaDemoRoute: typeof DemoScrollAreaDemoRoute
  DemoSidebarDemoRoute: typeof DemoSidebarDemoRoute
  DemoTableDemoRoute: typeof DemoTableDemoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTestRoute: typeof DemoTestRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/test': {
      id: '/demo/test'
      path: '/demo/test'
      fullPath: '/demo/test'
      preLoaderRoute: typeof DemoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table-demo': {
      id: '/demo/table-demo'
      path: '/demo/table-demo'
      fullPath: '/demo/table-demo'
      preLoaderRoute: typeof DemoTableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sidebar-demo': {
      id: '/demo/sidebar-demo'
      path: '/demo/sidebar-demo'
      fullPath: '/demo/sidebar-demo'
      preLoaderRoute: typeof DemoSidebarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/scroll-area-demo': {
      id: '/demo/scroll-area-demo'
      path: '/demo/scroll-area-demo'
      fullPath: '/demo/scroll-area-demo'
      preLoaderRoute: typeof DemoScrollAreaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/modal-test': {
      id: '/demo/modal-test'
      path: '/demo/modal-test'
      fullPath: '/demo/modal-test'
      preLoaderRoute: typeof DemoModalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form-test': {
      id: '/demo/form-test'
      path: '/demo/form-test'
      fullPath: '/demo/form-test'
      preLoaderRoute: typeof DemoFormTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/context-menu-demo': {
      id: '/demo/context-menu-demo'
      path: '/demo/context-menu-demo'
      fullPath: '/demo/context-menu-demo'
      preLoaderRoute: typeof DemoContextMenuDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/collapsible-demo': {
      id: '/demo/collapsible-demo'
      path: '/demo/collapsible-demo'
      fullPath: '/demo/collapsible-demo'
      preLoaderRoute: typeof DemoCollapsibleDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts/': {
      id: '/admin/contracts/'
      path: '/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AdminContractsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/new': {
      id: '/admin/groups/new'
      path: '/groups/new'
      fullPath: '/admin/groups/new'
      preLoaderRoute: typeof AdminGroupsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/$groupId': {
      id: '/admin/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AdminGroupsGroupIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts/new': {
      id: '/admin/contracts/new'
      path: '/contracts/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof AdminContractsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts/$contractId': {
      id: '/admin/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/admin/contracts/$contractId'
      preLoaderRoute: typeof AdminContractsContractIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/modules/': {
      id: '/admin/settings/modules/'
      path: '/settings/modules'
      fullPath: '/admin/settings/modules/'
      preLoaderRoute: typeof AdminSettingsModulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/fonts/': {
      id: '/admin/settings/fonts/'
      path: '/settings/fonts'
      fullPath: '/admin/settings/fonts/'
      preLoaderRoute: typeof AdminSettingsFontsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/': {
      id: '/admin/settings/app-shells/'
      path: '/settings/app-shells'
      fullPath: '/admin/settings/app-shells/'
      preLoaderRoute: typeof AdminSettingsAppShellsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/trials/': {
      id: '/admin/assets/trials/'
      path: '/assets/trials'
      fullPath: '/admin/assets/trials/'
      preLoaderRoute: typeof AdminAssetsTrialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/': {
      id: '/admin/assets/team-members/'
      path: '/assets/team-members'
      fullPath: '/admin/assets/team-members/'
      preLoaderRoute: typeof AdminAssetsTeamMembersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/': {
      id: '/admin/assets/places/'
      path: '/assets/places'
      fullPath: '/admin/assets/places/'
      preLoaderRoute: typeof AdminAssetsPlacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId/duplicate': {
      id: '/admin/users/$userId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/users/$userId/duplicate'
      preLoaderRoute: typeof AdminUsersUserIdDuplicateRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/settings/fonts/new': {
      id: '/admin/settings/fonts/new'
      path: '/settings/fonts/new'
      fullPath: '/admin/settings/fonts/new'
      preLoaderRoute: typeof AdminSettingsFontsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/fonts/$fontId': {
      id: '/admin/settings/fonts/$fontId'
      path: '/settings/fonts/$fontId'
      fullPath: '/admin/settings/fonts/$fontId'
      preLoaderRoute: typeof AdminSettingsFontsFontIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/new': {
      id: '/admin/settings/app-shells/new'
      path: '/settings/app-shells/new'
      fullPath: '/admin/settings/app-shells/new'
      preLoaderRoute: typeof AdminSettingsAppShellsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/$appShellId': {
      id: '/admin/settings/app-shells/$appShellId'
      path: '/settings/app-shells/$appShellId'
      fullPath: '/admin/settings/app-shells/$appShellId'
      preLoaderRoute: typeof AdminSettingsAppShellsAppShellIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/$groupId/duplicate': {
      id: '/admin/groups/$groupId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/groups/$groupId/duplicate'
      preLoaderRoute: typeof AdminGroupsGroupIdDuplicateRouteImport
      parentRoute: typeof AdminGroupsGroupIdRoute
    }
    '/admin/contracts/$contractId/duplicate': {
      id: '/admin/contracts/$contractId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/contracts/$contractId/duplicate'
      preLoaderRoute: typeof AdminContractsContractIdDuplicateRouteImport
      parentRoute: typeof AdminContractsContractIdRoute
    }
    '/admin/assets/trials/new': {
      id: '/admin/assets/trials/new'
      path: '/assets/trials/new'
      fullPath: '/admin/assets/trials/new'
      preLoaderRoute: typeof AdminAssetsTrialsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/trials/$trialId': {
      id: '/admin/assets/trials/$trialId'
      path: '/assets/trials/$trialId'
      fullPath: '/admin/assets/trials/$trialId'
      preLoaderRoute: typeof AdminAssetsTrialsTrialIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/new': {
      id: '/admin/assets/team-members/new'
      path: '/assets/team-members/new'
      fullPath: '/admin/assets/team-members/new'
      preLoaderRoute: typeof AdminAssetsTeamMembersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/team-members/$teamId': {
      id: '/admin/assets/team-members/$teamId'
      path: '/assets/team-members/$teamId'
      fullPath: '/admin/assets/team-members/$teamId'
      preLoaderRoute: typeof AdminAssetsTeamMembersTeamIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/new': {
      id: '/admin/assets/places/new'
      path: '/assets/places/new'
      fullPath: '/admin/assets/places/new'
      preLoaderRoute: typeof AdminAssetsPlacesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/places/$placeId': {
      id: '/admin/assets/places/$placeId'
      path: '/assets/places/$placeId'
      fullPath: '/admin/assets/places/$placeId'
      preLoaderRoute: typeof AdminAssetsPlacesPlaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/app-shells/$appShellId/duplicate': {
      id: '/admin/settings/app-shells/$appShellId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/settings/app-shells/$appShellId/duplicate'
      preLoaderRoute: typeof AdminSettingsAppShellsAppShellIdDuplicateRouteImport
      parentRoute: typeof AdminSettingsAppShellsAppShellIdRoute
    }
    '/admin/assets/trials/$trialId/duplicate': {
      id: '/admin/assets/trials/$trialId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/trials/$trialId/duplicate'
      preLoaderRoute: typeof AdminAssetsTrialsTrialIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsTrialsTrialIdRoute
    }
    '/admin/assets/team-members/$teamId/duplicate': {
      id: '/admin/assets/team-members/$teamId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/team-members/$teamId/duplicate'
      preLoaderRoute: typeof AdminAssetsTeamMembersTeamIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsTeamMembersTeamIdRoute
    }
    '/admin/assets/places/$placeId/duplicate': {
      id: '/admin/assets/places/$placeId/duplicate'
      path: '/duplicate'
      fullPath: '/admin/assets/places/$placeId/duplicate'
      preLoaderRoute: typeof AdminAssetsPlacesPlaceIdDuplicateRouteImport
      parentRoute: typeof AdminAssetsPlacesPlaceIdRoute
    }
  }
}

interface AdminContractsContractIdRouteChildren {
  AdminContractsContractIdDuplicateRoute: typeof AdminContractsContractIdDuplicateRoute
}

const AdminContractsContractIdRouteChildren: AdminContractsContractIdRouteChildren =
  {
    AdminContractsContractIdDuplicateRoute:
      AdminContractsContractIdDuplicateRoute,
  }

const AdminContractsContractIdRouteWithChildren =
  AdminContractsContractIdRoute._addFileChildren(
    AdminContractsContractIdRouteChildren,
  )

interface AdminGroupsGroupIdRouteChildren {
  AdminGroupsGroupIdDuplicateRoute: typeof AdminGroupsGroupIdDuplicateRoute
}

const AdminGroupsGroupIdRouteChildren: AdminGroupsGroupIdRouteChildren = {
  AdminGroupsGroupIdDuplicateRoute: AdminGroupsGroupIdDuplicateRoute,
}

const AdminGroupsGroupIdRouteWithChildren =
  AdminGroupsGroupIdRoute._addFileChildren(AdminGroupsGroupIdRouteChildren)

interface AdminUsersUserIdRouteChildren {
  AdminUsersUserIdDuplicateRoute: typeof AdminUsersUserIdDuplicateRoute
}

const AdminUsersUserIdRouteChildren: AdminUsersUserIdRouteChildren = {
  AdminUsersUserIdDuplicateRoute: AdminUsersUserIdDuplicateRoute,
}

const AdminUsersUserIdRouteWithChildren =
  AdminUsersUserIdRoute._addFileChildren(AdminUsersUserIdRouteChildren)

interface AdminAssetsPlacesPlaceIdRouteChildren {
  AdminAssetsPlacesPlaceIdDuplicateRoute: typeof AdminAssetsPlacesPlaceIdDuplicateRoute
}

const AdminAssetsPlacesPlaceIdRouteChildren: AdminAssetsPlacesPlaceIdRouteChildren =
  {
    AdminAssetsPlacesPlaceIdDuplicateRoute:
      AdminAssetsPlacesPlaceIdDuplicateRoute,
  }

const AdminAssetsPlacesPlaceIdRouteWithChildren =
  AdminAssetsPlacesPlaceIdRoute._addFileChildren(
    AdminAssetsPlacesPlaceIdRouteChildren,
  )

interface AdminAssetsTeamMembersTeamIdRouteChildren {
  AdminAssetsTeamMembersTeamIdDuplicateRoute: typeof AdminAssetsTeamMembersTeamIdDuplicateRoute
}

const AdminAssetsTeamMembersTeamIdRouteChildren: AdminAssetsTeamMembersTeamIdRouteChildren =
  {
    AdminAssetsTeamMembersTeamIdDuplicateRoute:
      AdminAssetsTeamMembersTeamIdDuplicateRoute,
  }

const AdminAssetsTeamMembersTeamIdRouteWithChildren =
  AdminAssetsTeamMembersTeamIdRoute._addFileChildren(
    AdminAssetsTeamMembersTeamIdRouteChildren,
  )

interface AdminAssetsTrialsTrialIdRouteChildren {
  AdminAssetsTrialsTrialIdDuplicateRoute: typeof AdminAssetsTrialsTrialIdDuplicateRoute
}

const AdminAssetsTrialsTrialIdRouteChildren: AdminAssetsTrialsTrialIdRouteChildren =
  {
    AdminAssetsTrialsTrialIdDuplicateRoute:
      AdminAssetsTrialsTrialIdDuplicateRoute,
  }

const AdminAssetsTrialsTrialIdRouteWithChildren =
  AdminAssetsTrialsTrialIdRoute._addFileChildren(
    AdminAssetsTrialsTrialIdRouteChildren,
  )

interface AdminSettingsAppShellsAppShellIdRouteChildren {
  AdminSettingsAppShellsAppShellIdDuplicateRoute: typeof AdminSettingsAppShellsAppShellIdDuplicateRoute
}

const AdminSettingsAppShellsAppShellIdRouteChildren: AdminSettingsAppShellsAppShellIdRouteChildren =
  {
    AdminSettingsAppShellsAppShellIdDuplicateRoute:
      AdminSettingsAppShellsAppShellIdDuplicateRoute,
  }

const AdminSettingsAppShellsAppShellIdRouteWithChildren =
  AdminSettingsAppShellsAppShellIdRoute._addFileChildren(
    AdminSettingsAppShellsAppShellIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminContractsContractIdRoute: typeof AdminContractsContractIdRouteWithChildren
  AdminContractsNewRoute: typeof AdminContractsNewRoute
  AdminGroupsGroupIdRoute: typeof AdminGroupsGroupIdRouteWithChildren
  AdminGroupsNewRoute: typeof AdminGroupsNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRouteWithChildren
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminContractsIndexRoute: typeof AdminContractsIndexRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminAssetsPlacesPlaceIdRoute: typeof AdminAssetsPlacesPlaceIdRouteWithChildren
  AdminAssetsPlacesNewRoute: typeof AdminAssetsPlacesNewRoute
  AdminAssetsTeamMembersTeamIdRoute: typeof AdminAssetsTeamMembersTeamIdRouteWithChildren
  AdminAssetsTeamMembersNewRoute: typeof AdminAssetsTeamMembersNewRoute
  AdminAssetsTrialsTrialIdRoute: typeof AdminAssetsTrialsTrialIdRouteWithChildren
  AdminAssetsTrialsNewRoute: typeof AdminAssetsTrialsNewRoute
  AdminSettingsAppShellsAppShellIdRoute: typeof AdminSettingsAppShellsAppShellIdRouteWithChildren
  AdminSettingsAppShellsNewRoute: typeof AdminSettingsAppShellsNewRoute
  AdminSettingsFontsFontIdRoute: typeof AdminSettingsFontsFontIdRoute
  AdminSettingsFontsNewRoute: typeof AdminSettingsFontsNewRoute
  AdminAssetsPlacesIndexRoute: typeof AdminAssetsPlacesIndexRoute
  AdminAssetsTeamMembersIndexRoute: typeof AdminAssetsTeamMembersIndexRoute
  AdminAssetsTrialsIndexRoute: typeof AdminAssetsTrialsIndexRoute
  AdminSettingsAppShellsIndexRoute: typeof AdminSettingsAppShellsIndexRoute
  AdminSettingsFontsIndexRoute: typeof AdminSettingsFontsIndexRoute
  AdminSettingsModulesIndexRoute: typeof AdminSettingsModulesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminContractsContractIdRoute: AdminContractsContractIdRouteWithChildren,
  AdminContractsNewRoute: AdminContractsNewRoute,
  AdminGroupsGroupIdRoute: AdminGroupsGroupIdRouteWithChildren,
  AdminGroupsNewRoute: AdminGroupsNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRouteWithChildren,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminContractsIndexRoute: AdminContractsIndexRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminAssetsPlacesPlaceIdRoute: AdminAssetsPlacesPlaceIdRouteWithChildren,
  AdminAssetsPlacesNewRoute: AdminAssetsPlacesNewRoute,
  AdminAssetsTeamMembersTeamIdRoute:
    AdminAssetsTeamMembersTeamIdRouteWithChildren,
  AdminAssetsTeamMembersNewRoute: AdminAssetsTeamMembersNewRoute,
  AdminAssetsTrialsTrialIdRoute: AdminAssetsTrialsTrialIdRouteWithChildren,
  AdminAssetsTrialsNewRoute: AdminAssetsTrialsNewRoute,
  AdminSettingsAppShellsAppShellIdRoute:
    AdminSettingsAppShellsAppShellIdRouteWithChildren,
  AdminSettingsAppShellsNewRoute: AdminSettingsAppShellsNewRoute,
  AdminSettingsFontsFontIdRoute: AdminSettingsFontsFontIdRoute,
  AdminSettingsFontsNewRoute: AdminSettingsFontsNewRoute,
  AdminAssetsPlacesIndexRoute: AdminAssetsPlacesIndexRoute,
  AdminAssetsTeamMembersIndexRoute: AdminAssetsTeamMembersIndexRoute,
  AdminAssetsTrialsIndexRoute: AdminAssetsTrialsIndexRoute,
  AdminSettingsAppShellsIndexRoute: AdminSettingsAppShellsIndexRoute,
  AdminSettingsFontsIndexRoute: AdminSettingsFontsIndexRoute,
  AdminSettingsModulesIndexRoute: AdminSettingsModulesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  DemoCollapsibleDemoRoute: DemoCollapsibleDemoRoute,
  DemoContextMenuDemoRoute: DemoContextMenuDemoRoute,
  DemoFormTestRoute: DemoFormTestRoute,
  DemoModalTestRoute: DemoModalTestRoute,
  DemoScrollAreaDemoRoute: DemoScrollAreaDemoRoute,
  DemoSidebarDemoRoute: DemoSidebarDemoRoute,
  DemoTableDemoRoute: DemoTableDemoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTestRoute: DemoTestRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
